CREATE TABLE IF NOT EXISTS `saida2` (
  `id` int NOT NULL AUTO_INCREMENT,
  `dataHora` datetime NOT NULL,
  `tag` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8